# Default
asynctweets_homepage:
    path:  /
    defaults: { _controller: AsyncTweetsBundle:Default:index }

asynctweets_tweets_sinceTweetId:
    path:  /sinceId/{firstTweetId}
    defaults: { _controller: AsyncTweetsBundle:Default:index }
    requirements:
        firstTweetId: \d+

asynctweets_reset_cookie:
    path:  /resetCookie
    defaults: { _controller: AsyncTweetsBundle:Default:resetCookie }

asynctweets_tweets_delete:
    path:  /tweets/delete/
    defaults: { _controller: AsyncTweetsBundle:Default:deleteLessThan }
