checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/
  paths:
    - src/

build:
  environment:
    php:
      version: 7.2
  dependencies:
    override:
      -
        command: 'SYMFONY_VERSION="^4.4" make composer-require-symfony-version'
      -
        command: 'make composer-install'
        idle_timeout: 900
  tests:
    override:
      -
        command: 'make phpspec'
      -
        command: './vendor/bin/phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
      -
        command: 'make behat'
