checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/
  paths:
    - src/

build:
  environment:
    php:
      version: 7.1
  dependencies:
    override:
      -
        command: 'composer require symfony/config:^4.4 symfony/form:^4.4 symfony/framework-bundle:^4.4 symfony/templating:^4.4 symfony/security-csrf:^4.4 symfony/var-dumper:^4.4 --no-update'
      -
        command: 'composer install --no-interaction -vv --profile --no-progress'
        idle_timeout: 900
  tests:
    override:
      -
        command: './vendor/bin/phpspec run --format=pretty'
      -
        command: './vendor/bin/phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
      -
        command: './vendor/bin/behat --colors --strict --format=progress -vv'
