checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - Tests/*
    - Command/StatusesHomeTimelineTestCommand.php
  paths:
    - Command/*
    - Controller/*
    - Entity/*
    - Utils/*
    - AsyncTweetsBundle.php

build:
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
