sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 5

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  #~ - SYMFONY_VERSION="3.0.*"

#~ matrix:
  #~ allow_failures:
    #~ - env: SYMFONY_VERSION="3.0.*"

addons:
  apt:
    packages:
      - php5-sqlite

# Only generate code coverage for the current versions of PHP and Symfony
# https://github.com/doctrine/doctrine2/blob/3570f4a49afc7e98fed71e0596dded6a39d4fd7b/.travis.yml#L16
before_install: if [[ $TRAVIS_PHP_VERSION = '5.6' && $SYMFONY_VERSION = '2.8.*' ]]; then DEPENDENCY='"codeclimate/php-test-reporter:dev-master"'; PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else DEPENDENCY=""; PHPUNIT_FLAGS=""; fi

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} $DEPENDENCY

script: php ./vendor/bin/phpunit $PHPUNIT_FLAGS

# Only send code coverage if it has been generated
after_success: if [[ $PHPUNIT_FLAGS != "" ]]; then php ./vendor/bin/test-reporter; fi
