sudo: false

language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.1.*"

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"

# Only send code coverage to Code Climate for the current versions of PHP and Symfony LTS
# https://github.com/doctrine/doctrine2/blob/3570f4a49afc7e98fed71e0596dded6a39d4fd7b/.travis.yml#L16
before_install:
 - if [[ $TRAVIS_PHP_VERSION = '7.0' && $SYMFONY_VERSION = '2.8.*' ]]; then DEPENDENCY="codeclimate/php-test-reporter:~0.3 satooshi/php-coveralls:~1.0"; PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else DEPENDENCY=""; PHPUNIT_FLAGS=""; fi
 - if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'hhvm' && $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi
 - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
 - php composer-setup.php
 - php -r "unlink('composer-setup.php');"

install:
  - php composer.phar require --dev symfony/symfony:${SYMFONY_VERSION} $DEPENDENCY --no-update
  - php -d memory_limit=1536M composer.phar install --no-interaction -vv --profile --no-progress

script: php ./vendor/bin/phpunit $PHPUNIT_FLAGS && php ./vendor/bin/behat

# Only send code coverage if it has been generated
after_success:
 - if [[ $PHPUNIT_FLAGS != "" ]]; then php ./vendor/bin/test-reporter; fi
 - if [[ $PHPUNIT_FLAGS != "" ]]; then travis_retry php vendor/bin/coveralls -v --config .coveralls.yml; fi
