sudo: false

checks:
  php:
    code_rating: true
    duplication: true

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*-dev"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="2.8.*-dev"

addons:
  apt:
    packages:
    - php5-sqlite

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

script: php ./vendor/bin/phpunit
