language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"

# https://github.com/travis-ci/travis-ci/issues/1075#issuecomment-17136080
before_install:
  - sudo apt-get update
  - sudo apt-get install php5-sqlite

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer install --prefer-dist

script: phpunit
