sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"

addons:
  apt:
    packages:
    - php5-sqlite

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

script: phpunit
