sudo: false

language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION="2.7.*"
    - php: hhvm
      env: SYMFONY_VERSION="2.8.*"
    - php: hhvm
      env: SYMFONY_VERSION="3.0.*"

# Only send code coverage to Code Climate for the current versions of PHP and Symfony LTS
# https://github.com/doctrine/doctrine2/blob/3570f4a49afc7e98fed71e0596dded6a39d4fd7b/.travis.yml#L16
before_install:
 - if [[ $TRAVIS_PHP_VERSION = '7.0' && $SYMFONY_VERSION = '2.8.*' ]]; then DEPENDENCY="codeclimate/php-test-reporter:~0.3 satooshi/php-coveralls:~1.0"; PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else DEPENDENCY=""; PHPUNIT_FLAGS=""; fi
 - if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'hhvm' && $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} $DEPENDENCY

script: php ./vendor/bin/phpunit $PHPUNIT_FLAGS

# Only send code coverage if it has been generated
after_success:
 - if [[ $PHPUNIT_FLAGS != "" ]]; then php ./vendor/bin/test-reporter; fi
 - if [[ $PHPUNIT_FLAGS != "" ]]; then travis_retry php vendor/bin/coveralls -v --config .coveralls.yml; fi
