dist: trusty
sudo: false

language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.2.*"

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.1.*"

# Only send code coverage to Code Climate for the current versions of PHP and Symfony LTS
# https://github.com/doctrine/doctrine2/blob/3570f4a49afc7e98fed71e0596dded6a39d4fd7b/.travis.yml#L16
before_install:
 - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
 - if [[ $TRAVIS_PHP_VERSION = '7.0' && $SYMFONY_VERSION = '2.8.*' ]]; then DEPENDENCY="codeclimate/php-test-reporter:~0.3 satooshi/php-coveralls:~1.0"; PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else DEPENDENCY=""; PHPUNIT_FLAGS=""; fi
 - if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'hhvm' && $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer require --dev symfony/symfony:${SYMFONY_VERSION} $DEPENDENCY --no-update
  - composer install --no-interaction -vv --profile --no-progress

script: php ./vendor/bin/phpunit $PHPUNIT_FLAGS && php ./vendor/bin/behat

# Only send code coverage if it has been generated
after_success:
 - if [[ $PHPUNIT_FLAGS != "" ]]; then php ./vendor/bin/test-reporter; fi
 - if [[ $PHPUNIT_FLAGS != "" ]]; then travis_retry php vendor/bin/coveralls -v --config .coveralls.yml; fi
