build: false
clone_depth: 1
clone_folder: c:\projects\asynctweetsbundle

# https://github.com/travis-ci/travis-ci/issues/3005#issuecomment-71320541
skip_commits:
    message: /.*\[skip appveyor\].*/

cache:
    - '%LOCALAPPDATA%\Composer\files'
    - c:\projects\asynctweetsbundle\composer.phar

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)
    - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
    - mkdir c:\php && cd c:\php
    - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
    - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.6.29-Win32-VC11-x86.zip
    - 7z x php-5.6.29-Win32-VC11-x86.zip -y >nul
    - del /Q *.zip
    - copy /Y php.ini-development php.ini
    - echo max_execution_time=600 >> php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo zend_extension=php_opcache.dll >> php.ini
    - echo opcache.enable_cli=1 >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo apc.enable_cli=1 >> php.ini
    - echo extension=php_intl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - echo extension=php_pdo_sqlite.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo curl.cainfo=c:\php\cacert.pem >> php.ini
    - cd c:\projects\asynctweetsbundle
    - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.3.2/composer.phar)
    - php composer.phar self-update -vvv
    - php composer.phar require "symfony/symfony:3.4.*" --no-progress --ansi

test_script:
    - cd c:\projects\asynctweetsbundle
    - vendor/bin/phpspec run --format=pretty || SET X=!errorlevel!
    - vendor/bin/phpunit --colors=never || SET X=!errorlevel!
    - vendor/bin/behat || SET X=!errorlevel!
    - exit %X%
