build: false
shallow_clone: true
platform: x64
clone_folder: c:\projects\asynctweetsbundle

# https://github.com/travis-ci/travis-ci/issues/3005#issuecomment-71320541
skip_commits:
    message: /.*\[skip appveyor\].*/
    
cache:
    - c:\tools\php -> appveyor.yml

init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\tools\php (SET PHP=0)
    - IF %PHP%==1 cinst -y OpenSSL.Light
    - IF %PHP%==1 cinst -y php
    - cd c:\tools\php
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_intl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\asynctweetsbundle
    - composer require "symfony/symfony:2.8.*" --no-progress

test_script:
    - cd c:\projects\asynctweetsbundle
    - vendor/bin/phpunit
