<?php

namespace AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    private $nbTweets = 10;
    
    public function getWithUsers($page = 1)
    {
        $firstResult = (($page - 1) * $this->nbTweets);
        
        $qb = $this->createQueryBuilder('t')
            ->select('t, user')
            ->innerJoin('t.user', 'user')
            
            ->orderBy('t.id', 'DESC')
            
            ->setFirstResult($firstResult)
            ->setMaxResults($this->nbTweets)
        ;
        
        return $qb->getQuery()->getResult();
    }
    
    public function getWithUsersAndMedias($firstTweetId = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t, user, medias')
            ->innerJoin('t.user', 'user')
            ->leftJoin('t.medias', 'medias')
            
            ->orderBy('t.id', 'ASC')
            
            ->setFirstResult(0)
            ->setMaxResults($this->nbTweets)
        ;
        
        if (! is_null($firstTweetId))
        {
            $qb = $qb->where(
                $qb->expr()->gte('t.id', $firstTweetId)
            );
        }
        
        return $qb->getQuery()->getResult();
    }
    
    private function getQueryBuilder()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.id')
            
            ->setFirstResult($this->nbTweets - 1)
            ->setMaxResults(1)
        ;
        
        return($qb);
    }
    
    /**
     * Return previous page tweet id
     */
    private function getPreviousTweetId($tweetId)
    {
        $qb = $this->getQueryBuilder()
            ->where('t.id < :tweetId')
            ->setParameter(':tweetId', $tweetId)
            
            ->orderBy('t.id', 'DESC')
        ;
        
        return($this->getIdOrNull($qb));
    }
    
    /**
     * Return next page tweet id
     */
    private function getNextTweetId($tweetId)
    {
        $qb = $this->getQueryBuilder()
            ->where('t.id > :tweetId')
            ->setParameter(':tweetId', $tweetId)
            
            ->orderBy('t.id', 'ASC')
        ;
        
        return($this->getIdOrNull($qb));
    }
    
    private function getIdOrNull($qb)
    {
        $result = $qb->getQuery()->getOneOrNullResult();
        
        return(is_array($result) ? $result['id'] : null);
    }
    
    public function getPreviousAndNextTweetId($tweetId)
    {
        return(array(
            $this->getPreviousTweetId($tweetId),
            $this->getNextTweetId($tweetId)
        ));
    }
    
    public function countPendingTweets($lastTweetId = null)
    {
        $qb = $this->createQueryBuilder('t');
        
        $qb = $qb
            ->add('select', $qb->expr()->count('t.id'))
        ;
        
        if (! is_null($lastTweetId))
        {
            $qb = $qb
                ->where(
                    $qb->expr()->gte('t.id', $lastTweetId)
                )
            ;
        }
        
        # return result of "COUNT()" query
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getLastTweet()
    {
        $qb = $this->createQueryBuilder('t');
        
        $qb = $qb
            ->addOrderBy('t.id', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1)
        ;
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
