<?php

namespace AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends EntityRepository
{
    private $nbTweets = 10;
    
    public function getWithUsers($page = 1)
    {
        $firstResult = (($page - 1) * $this->nbTweets);
        
        $qb = $this->createQueryBuilder('t')
            ->select('t, user')
            ->innerJoin('t.user', 'user')
            
            ->addSelect('rt')
            ->leftJoin('t.retweeted_status', 'rt')
            
            ->addSelect('rt_user')
            ->leftJoin('rt.user', 'rt_user')
            
            // Ignore tweets that were only retweeted
            ->where('t.in_timeline = 1')
            
            ->orderBy('t.id', 'DESC')
            
            ->setFirstResult($firstResult)
            ->setMaxResults($this->nbTweets)
        ;
        
        return $qb->getQuery()->getResult();
    }
    
    public function getWithUsersAndMedias($firstTweetId = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t, user, medias')
            ->innerJoin('t.user', 'user')
            ->leftJoin('t.medias', 'medias')
            
            ->addSelect('rt')
            ->leftJoin('t.retweeted_status', 'rt')
            
            ->addSelect('rt_user')
            ->leftJoin('rt.user', 'rt_user')
            
            // Ignore tweets that were only retweeted
            ->where('t.in_timeline = 1')
            
            ->orderBy('t.id', 'ASC')
            
            ->setFirstResult(0)
            ->setMaxResults($this->nbTweets)
        ;
        
        if (! is_null($firstTweetId))
        {
            $qb = $qb->andWhere(
                $qb->expr()->gte('t.id', $firstTweetId)
            );
        }
        
        return $qb->getQuery()->getResult();
    }
    
    /**
     * @param string $condition
     * @param string $order
     */
    private function getTweetId($condition, $order, $tweetId)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.id')
            
            ->where('t.id '.$condition.' :tweetId')
            ->setParameter(':tweetId', $tweetId)
            
            ->orderBy('t.id', $order)
            
            ->setFirstResult($this->nbTweets - 1)
            ->setMaxResults(1)
        ;
        
        $result = $qb->getQuery()->getOneOrNullResult();
        
        return($this->getIdOrNull($result));
    }
    
    private function getIdOrNull($result)
    {
        return(is_array($result) ? $result['id'] : null);
    }
    
    public function getPreviousAndNextTweetId($tweetId)
    {
        return(array(
            $this->getTweetId('<', 'DESC', $tweetId),
            $this->getTweetId('>', 'ASC', $tweetId)
        ));
    }
    
    public function countPendingTweets($lastTweetId = null)
    {
        $qb = $this->createQueryBuilder('t');
        
        $qb->add('select', $qb->expr()->count('t.id'));
        
        if (! is_null($lastTweetId))
        {
            $qb->where(
                $qb->expr()->gte('t.id', $lastTweetId)
            );
        }
        
        # return result of "COUNT()" query
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getLastTweet()
    {
        $qb = $this->createQueryBuilder('t')
            ->addOrderBy('t.id', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1)
        ;
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    private function getTweetsLessThanId($tweetId)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t, m')
            ->leftJoin('t.medias', 'm')
            ->where('t.id < :tweetId')
            ->setParameter(':tweetId', $tweetId)
            
            ->orderBy('t.id', 'DESC')
        ;
        
        return($qb->getQuery()->getResult());
    }
    
    /**
     * Remove Media not associated to any Tweet
     */
    private function removeOrphanMedias(Media $media)
    {
        if (count($media->getTweets()) == 0)
        {
            $this->_em->remove($media);
        }
    }
    
    public function deleteTweetsLessThanId($tweetId)
    {
        $count = 0;
        
        foreach ($this->getTweetsLessThanId($tweetId) as $tweet)
        {
            foreach ($tweet->getMedias() as $media)
            {
                $tweet->removeMedia($media);
                $this->removeOrphanMedias($media);
            }
            
            $this->_em->remove($tweet);
            
            $count++;
        }
        
        $this->_em->flush();
        
        return($count);
    }
}
