version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3-buster-browsers
    steps:
      - checkout
      - run: echo 'memory_limit = -1' | sudo tee -a /usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - run: SYMFONY_VERSION="^4.4" make composer-require-symfony-version
      - restore_cache:
          keys:
          - composer-v1-{{ .Branch }}
          # fallback to using the latest cache if no exact match is found
          - composer-v1-
      - run: make composer-install
      - run: make phpspec
      - run: mkdir -p ~/phpunit
      - run: php ./vendor/bin/phpunit --log-junit ~/phpunit/junit.xml tests
      - run: make behat
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
      - save_cache:
          key: composer-v1-{{ .Branch }}
          paths:
              - ~/.composer/cache
